config/routes.rb
Rails.application.routes.draw do
  resources :items
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  # get metrics for prometheus
  get '/metrics', to: 'metrics#index'
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
  after_create :increment_items_created_metric

  private

  def increment_items_created_metric
    Metrics.items_created.increment
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # Changes to the importmap will invalidate the etag for HTML responses
  stale_when_importmap_changes
end

app/controllers/items_controller.rb
require 'prometheus_exporter/metric'

class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]

  # GET /items or /items.json
  def index
    @items = Item.all
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: "Item was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy!

    respond_to do |format|
      format.html { redirect_to items_path, notice: "Item was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  def index
    ITEMS_COUNTER.observe(1)

    start = Process.clock_gettime(Process::CLOCK_MONOTONIC)
    @items = Item.all
    duration = Process.clock_gettime(Process::CLOCK_MONOTONIC) - start

    ITEMS_HISTOGRAM.observe(duration)

    render json: @items
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.expect(item: [ :title, :description ])
    end
end

app/controllers/metrics_controller.rb
class MetricsController < ApplicationController
  def index
    render plain: PROMETHEUS.metrics.map(&:to_s).join("\n")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item) do |form| %>
  <% if item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.textarea :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/items/_item.html.erb
<div id="<%= dom_id item %>">
  <div>
    <strong>Title:</strong>
    <%= item.title %>
  </div>

  <div>
    <strong>Description:</strong>
    <%= item.description %>
  </div>

</div>

app/views/items/edit.html.erb
<% content_for :title, "Editing item" %>

<h1>Editing item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Show this item", @item %> |
  <%= link_to "Back to items", items_path %>
</div>

app/views/items/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Items" %>

<h1>Items</h1>

<div id="items">
  <% @items.each do |item| %>
    <%= render item %>
    <p>
      <%= link_to "Show this item", item %>
    </p>
  <% end %>
</div>

<%= link_to "New item", new_item_path %>

app/views/items/new.html.erb
<% content_for :title, "New item" %>

<h1>New item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Back to items", items_path %>
</div>

app/views/items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @item %>

<div>
  <%= link_to "Edit this item", edit_item_path(@item) %> |
  <%= link_to "Back to items", items_path %>

  <%= button_to "Destroy this item", @item, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Recipe" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Recipe">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>